name: check-status-action
description: 'send check status'
author: 'n-iino'
inputs:
  github-token:
    required: true
    description: 'github token'
  name:
    required: true
    description: 'name of job'
  status:
    required: true
  conclusion:
    required: true
  run-title:
    required: false
  summary:
    required: false
  detailsUrl:
    required: false
  head-sha:
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
